### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by onepiecefyf** [baidu/openrasp#432]
# Bug report
我准备使用外部驱动连接数据库，但是连接过程中发现一个问题，无法加载我们的驱动，希望可以加载我们自己的驱动
操作系统：ubuntu 22
应用：springmvc
java：JDK1.8
 

外部驱动：daps-client-0.2.0-HPF-06011340.jar

驱动放置目录：
1、BES部署目录
ubuntu@ubuntu-virtual-machine:~/data/bes/BES910/lib$ pwd
/home/ubuntu/data/bes/BES910/lib
ubuntu@ubuntu-virtual-machine:~/data/bes/BES910/lib$ ls
bes-client.jar  bes-merge-jar.jar  daps-client-0.2.0-HPF-06011340.jar  iastool     mysql-connector-java-5.1.45.jar  plugins  sdk
bes-core.jar    bes-resource.jar   endorsed                            javaee.jar  patch                            schemas  system

2、实例目录
ubuntu@ubuntu-virtual-machine:~/data/bes/BES910/var/domains/domain3/nodes/Node3/instances/Server3/lib$ ls
apps  classes  daps-client-0.2.0-HPF-06011340.jar  databases  ext  mysql-connector-java-5.1.45.jar

控制台报错信息：
###|2023-06-06 14:02:819|com.bes.enterprise.console.resources.jdbc.action.JdbcConnectionPoolAction|threadId=66|SEVERE|com.bes.enterprise.console.pub.iirest.exception.RestfulException: java.lang.NoClassDefFoundError: Could not initialize class cn.bjca.daps.driver.DapsDriver
	at com.bes.enterprise.console.pub.iirest.util.RestResponse.getRestResponse(RestResponse.java:76)
	at com.bes.enterprise.console.pub.iirest.util.RestUtil.get(RestUtil.java:795)
	at com.bes.enterprise.console.resources.jdbc.action.JdbcConnectionPoolAction.pingConnectionPool(JdbcConnectionPoolAction.java:495)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:440)
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:428)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:936)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:838)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:812)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:726)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1530)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:300)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:174)
	at com.bes.enterprise.console.core.action.BaseActionFilter.doFilter(BaseActionFilter.java:80)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:213)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:223)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:213)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.filters.XssPreventionFilter.doFilter(XssPreventionFilter.java:56)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:213)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:241)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:133)

**Comment by CaledoniaProject** [comment]
这个跟openrasp似乎没有关系？
