### ISSUE TITLE
数据库连接池支持

### ISSUE THREAD

**Issue by CaledoniaProject** [baidu/openrasp#74]
由QQ群用户Aven提供，C3P0数据库连接池例子，待测试

[TestDB.zip](https://github.com/baidu/openrasp/files/1550142/TestDB.zip)

打好的war包，改下扩展名

[pool.war](https://github.com/baidu/openrasp/files/1550516/sqlconnectionpool.war.txt)

**Comment by CaledoniaProject** [comment]
经过测试，这个连接池并没有跨线程操作，所以OpenRASP依然能够拦截

快速测试，

```
sqlmap -u 'http://127.0.0.1:8080/pool/mysql?name=hello'
```

catalina 日志，

```
java.sql.SQLException: An SQLException was provoked by the following failure: com.fuxi.javaagent.exception.SecurityException: Request blocked by OpenRASP
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
```

**Comment by CaledoniaProject** [comment]
结论: 只要没有跨线程操作，都可以正常检测
