### ISSUE TITLE
rhino jdk8u162 兼容性问题

### ISSUE THREAD

**Issue by CaledoniaProject** [baidu/openrasp#98]
在最新的 `jdk8u162` 上运行 openrasp，会出现这个错误；`OpenJDK 1.7u171 (发布于 2018.02)` 也存在这个问题。

临时解决方案是降级到 `jdk8 update 144` 或者更低版本
http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html?printOnly=1

现在QA资源紧张，PHP版本还没有测试完成，所以要下下个版本发布

### 具体错误

堆栈信息

```
java.util.MissingResourceException: Can't find bundle for base name org.mozilla.javascript.resources.Messages, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
	at org.mozilla.javascript.ScriptRuntime$DefaultMessageProvider.getMessage(ScriptRuntime.java:4096)
	at org.mozilla.javascript.ScriptRuntime.getMessage(ScriptRuntime.java:4080)
	at org.mozilla.javascript.ScriptRuntime.getMessage1(ScriptRuntime.java:4034)
```

**Comment by tangyouyi1513** [comment]
目前打算通过拆包，来吧rhino引擎包使用单独的classloader加载起来，解决这个问题

**Comment by CaledoniaProject** [comment]
临时解决方案是降级到 jdk8 update 144 或者更低版本
http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html?printOnly=1

**Comment by CaledoniaProject** [comment]
今天发现，OpenJDK 1.7u171 (发布于 2018.02) 也存在这个问题

**Comment by CaledoniaProject** [comment]
现在QA资源紧张，PHP版本还没有测试完成，所以要下下个版本发布

**Comment by CaledoniaProject** [comment]
完成后，需要同时测试 JDK 9 ~ 10 的兼容性

**Comment by CaledoniaProject** [comment]
已解决，最晚下周三发版
